# Generated by Django 4.1.4 on 2022-12-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221206_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ('genre', 'title')},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('pub_date',)},
        ),
    ]
