# Generated by Django 2.2.16 on 2022-11-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='title_id',
            new_name='title',
        ),
    ]
