# Generated by Django 2.2.16 on 2022-11-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221127_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='score',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
