# Generated by Django 2.2.16 on 2022-11-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
